### ISSUE TITLE
ValueError: Cannot find supported backend: 'cgl'

### ISSUE THREAD

**Issue by pookzzz** [patriciogonzalezvivo/comfyui_glslnodes#8]
I had a fresh install of comfyUI using pinokio on a Mac M3 and I encountered this traceback:

Traceback (most recent call last):
  File "/Users/user/pinokio/api/comfyui.git/app/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/user/pinokio/api/comfyui.git/app/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/user/pinokio/api/comfyui.git/app/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/user/pinokio/api/comfyui.git/app/custom_nodes/comfyui_glslnodes/glsl_uniforms.py", line 32, in main
    context = Context()
  File "/Users/user/pinokio/api/comfyui.git/app/custom_nodes/comfyui_glslnodes/glsl_context.py", line 18, in __init__
    self.ctx = moderngl.create_context(
  File "/Users/user/pinokio/api/comfyui.git/app/env/lib/python3.10/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/Users/user/pinokio/api/comfyui.git/app/env/lib/python3.10/site-packages/glcontext/__init__.py", line 51, in get_backend_by_name
    raise ValueError("Cannot find supported backend: '{}'".format(name))
ValueError: Cannot find supported backend: 'cgl'

**Comment by patriciogonzalezvivo** [comment]
Hi @pookzzz! thanks for reporting this. I just push a change to see if it fixes (I'm using this in my linux machine, so not sure if it will work).
Do you mind manually pulling the last changes? By in the terminal doing

```
cd ComfyUI/custom_nodes/comfyui_glslnodes
git pull
```

Thank you

**Comment by pookzzz** [comment]
Hi Patricio,
I pulled and I can get it to work with version 100, but 120 and 130 gives me this error
<img width="1402" alt="Screenshot 2024-07-26 at 11 34 59 AM" src="https://github.com/user-attachments/assets/524b2148-4870-4e97-b6f2-5a00c6126e40">

**Comment by patriciogonzalezvivo** [comment]
what about 300 core and above?
